name: Push Changes to Hugging Face Space

on:
  push:
    branches:
      - main  # This triggers the workflow on push events to the main branch.

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          huggingface-cli login --token $HF_TOKEN --add-to-git-credential

      - name: Clone Hugging Face Space Repository
        run: |
          git clone https://huggingface.co/spaces/KedharNarayanan/Fit_RAG
          cd Fit_RAG

      - name: Commit and Push Changes
        run: |
          cd Fit_RAG
          git config --global kedharnarayanan@gmail.com
          git config --global KedharNarayanan
          git add .
          git commit -m "Update files"
          git push origin main
